Repository timmo001/home-panel, pull requests merged in 2019-10, with the labels that each got.

#557 Scale image to fit screen
  src/Components/Cards/Image.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface

#572 Updates
  api/package.json
  api/yarn.lock
  package.json
  yarn.lock
Labels: Hacktoberfest, Type: Maintenance

#583 Tweak grids
  src/Components/Overview/Overview.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface

#584 Theme Rework
  api/config/config.default.json
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/Item.tsx
  src/Components/HomeAssistant/Cards/Select.tsx
  src/Components/HomeAssistant/Utils/EntitySelect.tsx
  src/Components/Main.tsx
  src/Components/Onboarding.tsx
  src/Components/Utils/ColorWheel.tsx
  src/Components/Utils/parseTheme.tsx
  yarn.lock
Labels: Hacktoberfest, Type: Enhancement, User Interface

#586 Add chart labels on hover
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/EditCard/Entity.tsx
  src/Components/HomeAssistant/Cards/State.tsx
  src/Components/Visualisations/Chart.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface

#587 Add config for fonts and icons
  src/Components/Cards/Base.tsx
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/EditCard/Base.tsx
  src/Components/Configuration/EditCard/Entity.tsx
  src/Components/HomeAssistant/Cards/Light.tsx
  src/Components/HomeAssistant/Cards/Select.tsx
  src/Components/HomeAssistant/Cards/State.tsx
  src/Components/HomeAssistant/Cards/Toggle.tsx
  src/Components/Overview/Header/Header.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface

#594 Entity Improvements
  src/Components/Cards/Base.tsx
  src/Components/Configuration/EditCard/Entity.tsx
  src/Components/HomeAssistant/Cards/Climate.tsx
  src/Components/HomeAssistant/Cards/Entity.tsx
  src/Components/HomeAssistant/Cards/Number.tsx
  src/Components/HomeAssistant/HomeAssistant.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface

#598 News Feed
  package.json
  src/Components/Cards/Base.tsx
  src/Components/Cards/News.tsx
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/EditCard/Base.tsx
  src/Components/Configuration/EditCard/News.tsx
  src/Components/Configuration/Item.tsx
  src/Components/HomeAssistant/Cards/Light.tsx
  src/Components/HomeAssistant/Cards/Media.tsx
  src/Components/Utils/Select.tsx
  yarn.lock
Labels: Hacktoberfest, Type: Feature, User Interface

#604 Move link color to config
  api/config/config.default.json
  src/Components/Configuration/Config.tsx
  src/Components/Onboarding.tsx
  src/Style/index.css
Labels: Hacktoberfest, Type: Feature, User Interface

#603 Add RSS Feeds
  package.json
  src/Components/Cards/Base.tsx
  src/Components/Cards/RSS.tsx
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/EditCard/Base.tsx
  src/Components/Configuration/EditCard/RSS.tsx
  yarn.lock
Labels: Hacktoberfest, Type: Feature, User Interface

#606 Charts Rework
  package.json
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/EditCard/Entity.tsx
  src/Components/HomeAssistant/Cards/State.tsx
  src/Components/Visualisations/Chart.tsx
  yarn.lock
Labels: Hacktoberfest, Type: Enhancement, User Interface

#607 Add Backup and Restore Functionality
  src/Components/Configuration/Config.tsx
  src/Components/Configuration/Configuration.tsx
  src/Components/Configuration/Item.tsx
  src/Components/Main.tsx
Labels: Architecture, Hacktoberfest, Type: Feature, User Interface

#649 Controller
  api/src/hooks/process-config-update.ts
  api/src/hooks/process-config.ts
  api/src/hooks/process-controller.ts
  api/src/services/config/config.class.ts
  api/src/services/controller/controller.class.ts
  api/src/services/controller/controller.hooks.ts
  api/src/services/controller/controller.service.ts
  api/src/services/index.ts
  api/test/services/controller.test.ts
  src/Components/Cards/Base.tsx
  src/Components/Cards/Image.tsx
  src/Components/Configuration/EditCard/EditCard.tsx
  src/Components/Main.tsx
  src/Components/Onboarding.tsx
  src/Components/Overview/Overview.tsx
  src/Components/Utils/Command.tsx
Labels: API, Architecture, Hacktoberfest, Type: Feature, User Interface

#660 Fix CardActions button style for Safari
  src/Components/Cards/Base.tsx
Labels: Hacktoberfest, Type: Enhancement, User Interface
